name: workout_wizard
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  cloud_firestore: ^4.17.5
  cpf_cnpj_validator: ^2.0.0
  device_preview: ^1.2.0
  email_validator: ^2.1.17
  firebase_auth: ^4.19.6
  firebase_core: ^2.31.1
  font_awesome_flutter: ^10.1.0
  flutter:
    sdk: flutter
  http: ^1.2.1
  intl: ^0.19.0
  mask_text_input_formatter: ^2.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  url_launcher: ^6.1.11

flutter:
  uses-material-design: true
  assets:
    - images/ginasta-masculina-flexionando-os-bracos.png
    - images/home.png
    - images/objetivo.png
    - images/oferecer.png
    - images/autores.png
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
