// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRL1HT0Ag319iaPWtmGpO6WT5BpRCBAV8',
    appId: '1:903320001350:web:8265e10d5f00ee672aa347',
    messagingSenderId: '903320001350',
    projectId: 'workout-wizard-a528c',
    authDomain: 'workout-wizard-a528c.firebaseapp.com',
    storageBucket: 'workout-wizard-a528c.appspot.com',
    measurementId: 'G-4KHEEPM7J4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALpScMWu-WCcfs0rvtJoQKCwjmse3aYc8',
    appId: '1:903320001350:android:4f3699be6c7e3c812aa347',
    messagingSenderId: '903320001350',
    projectId: 'workout-wizard-a528c',
    storageBucket: 'workout-wizard-a528c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4jsMwVGVTsomRWdDHH8WXAHS3Szv2xs4',
    appId: '1:903320001350:ios:ca8f74a86d8c06262aa347',
    messagingSenderId: '903320001350',
    projectId: 'workout-wizard-a528c',
    storageBucket: 'workout-wizard-a528c.appspot.com',
    iosBundleId: 'com.example.workoutWizard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4jsMwVGVTsomRWdDHH8WXAHS3Szv2xs4',
    appId: '1:903320001350:ios:ca8f74a86d8c06262aa347',
    messagingSenderId: '903320001350',
    projectId: 'workout-wizard-a528c',
    storageBucket: 'workout-wizard-a528c.appspot.com',
    iosBundleId: 'com.example.workoutWizard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRL1HT0Ag319iaPWtmGpO6WT5BpRCBAV8',
    appId: '1:903320001350:web:76d1efa4d166925f2aa347',
    messagingSenderId: '903320001350',
    projectId: 'workout-wizard-a528c',
    authDomain: 'workout-wizard-a528c.firebaseapp.com',
    storageBucket: 'workout-wizard-a528c.appspot.com',
    measurementId: 'G-TJ4FYDEVJH',
  );
}
